version: '3.9'
services:
  php:
    build: 
      context: ./build/php-fpm/${PHP_VERSION}
      args:
        TIMEZONE: ${TIMEZONE}
        CHANGE_DEBIAN_SOURCE: ${CHANGE_DEBIAN_SOURCE}
        CHANGE_COMPOSER_SOURCE: ${CHANGE_COMPOSER_SOURCE}
    volumes:
      - ./conf/php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini:ro
      - ./conf/php/mysql.ini:/usr/local/etc/php/conf.d/mysql.ini:ro
      - ./conf/php/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      # - ${APP_CODE_PATH_HOST}:/var/www:rw
      # 容器中绑定的目录需要和nginx中保持一致
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}:rw
      - ./conf/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
    restart: always
    ports:
      - "9003:9003"
    expose:
      - 9000
    networks:
      - backend
  nginx:
    image: nginx:alpine
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}:rw
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./conf/nginx/log:/var/log/nginx:rw
    restart: always
    networks:
      - backend

networks:
  backend:
    # external: true